apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
  - job-init.yaml
configMapGenerator:
  - name: minio-init
    files:
      - init-bucket.sh
generatorOptions:
  disableNameSuffixHash: true
