/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recibe un evento de GitHub (firmado) y crea una notificacion. */
        post: operations["handleGithubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inbox de notificaciones. */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirma una notificacion (persiste confirmacion auditable). */
        post: operations["confirmRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado de una corrida. */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{run}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reporte post-mortem de una corrida. */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lee la ultima version de una politica (cualquier autenticado; 404 si nunca se escribio). */
        get: operations["getPolicy"];
        /** Define una politica (solo admin). */
        put: operations["setPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gates/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evalua los gates de una transicion de corrida (fail-closed; solo servicio a servicio). */
        post: operations["authorizeGate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulta del registro de auditoria. */
        get: operations["queryAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia sesion. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cierra la sesion. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sesion del token presentado (cuenta como uso para la inactividad). */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sesion por id publico. Un user solo ve la suya (403 si es ajena o no existe); un admin ve 404 si no existe. */
        get: operations["getSessionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista usuarios (solo admin). Nunca expone hashes ni secretos. */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        Session: {
            principal_id: string;
            /** @enum {string} */
            role: "user" | "admin";
            session_id: string;
            /** Format: date-time */
            expires_at: string;
        };
        Notification: {
            id: string;
            /** @enum {string} */
            github_event: "commit" | "pull_request" | "tag";
            repo: string;
            sha: string;
            artifact?: {
                /** @enum {string} */
                kind: "build-from-repo" | "published-image";
                ref: string;
            };
            /** @enum {string} */
            state: "pending" | "confirmed" | "rejected";
        };
        ConfirmationReceipt: {
            run_id: string;
            notification_id: string;
            confirmed_by: string;
            /** Format: date-time */
            confirmed_at: string;
        };
        Run: {
            id: string;
            /** @enum {string} */
            state: "confirmed" | "warm_ready" | "deploying" | "inferring" | "rehearsing" | "running" | "resetting" | "reporting" | "done" | "failed";
            trace_id?: string;
        };
        Report: {
            run_id: string;
            findings: {
                id: string;
                /** @enum {string} */
                severity: "low" | "medium" | "high" | "critical";
                summary: string;
            }[];
        };
        Policy: {
            value: {
                [key: string]: unknown;
            };
        };
        PolicyVersion: {
            name: string;
            version: number;
        };
        GateDecision: {
            allow: boolean;
            reason: string;
            audit_ref: string;
        };
        GateRequest: {
            run_id: string;
            from: string;
            to: string;
            target_namespace: string;
            workflow?: string;
            /** @enum {string} */
            confirmed?: "true" | "false" | "unknown";
            /** @enum {string} */
            reset_verified?: "true" | "false" | "unknown";
            /** @enum {string} */
            ensayo_passed?: "true" | "false" | "unknown";
            /** @enum {string} */
            workflow_allowed?: "true" | "false" | "unknown";
            /** @enum {string} */
            approval_recorded?: "true" | "false" | "unknown";
        };
        AuditEntry: {
            /** Format: date-time */
            at: string;
            actor: string;
            action: string;
            run_id?: string;
        };
    };
    responses: {
        /** @description Error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    handleGithubWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-Hub-Signature-256": string;
                "X-GitHub-Event": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Notificacion creada. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                state?: "pending" | "confirmed" | "rejected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de notificaciones. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    confirmRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    flows: string[];
                };
            };
        };
        responses: {
            /** @description Confirmacion registrada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmationReceipt"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Corrida. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reporte. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Politica vigente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    setPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            /** @description Politica versionada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyVersion"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    authorizeGate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GateRequest"];
            };
        };
        responses: {
            /** @description Decision (allow=false tambien es 200). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateDecision"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            413: components["responses"]["Error"];
            /** @description Error interno o auditoria imposible; siempre allow=false. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateDecision"];
                };
            };
        };
    };
    queryAudit: {
        parameters: {
            query?: {
                run?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entradas de auditoria. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    /** Format: password */
                    password: string;
                    otp?: string;
                };
            };
        };
        responses: {
            /** @description Sesion iniciada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        /** Format: date-time */
                        expires_at: string;
                        session_id?: string;
                    };
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesion cerrada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesion vigente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    getSessionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesion. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuarios. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        username: string;
                        /** @enum {string} */
                        role: "user" | "admin";
                    }[];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
}
