apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-run-controller
  namespace: aqs-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-warm-manager
  namespace: aqs-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-reset
  namespace: aqs-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aqs-runner
  namespace: aqs-test
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui-api
  namespace: aqs-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-intake
  namespace: aqs-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-governance
  namespace: aqs-system
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-identity
  namespace: aqs-system
automountServiceAccountToken: false
